---
- name: Add Logstash repository
  template:
    src: logstash.repo.j2
    dest: /etc/yum.repos.d/logstash.repo
- name: Install Logstash
  yum:
    name: logstash
    state: present
- name: Start and enable logstash
  service:
    name: logstash
    state: started
    enabled: yes
- name: Configure OpenSSL
  template:
    src: openssl.cnf.j2
    dest: /etc/pki/tls/openssl.cnf
- name: Create self-signed SSL cert
  command: openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt
  args:
    chdir: /etc/pki/tls
- name: Copy self-signed cert to local
  fetch:
    src: /etc/pki/tls/certs/logstash-forwarder.crt
    dest: /tmp/logstash-forwarder.crt
    flat: yes
    validate_checksum: yes
- name: Add Logstash configuration file
  template:
    src: logger.conf.j2
    dest: /etc/logstash/conf.d/logger.conf
- name: Creates patterns directory
  file:
    path: /opt/logstash/patterns
    state: directory
- name: Add AUDITLOGLEVEL to Logstash patterns
  template:
    src: AUDITLOGLEVEL.j2
    dest: /opt/logstash/patterns/AUDITLOGLEVEL
  notify: restart_logstash
